#!/bin/bash
#-----------------------------------I'm inside Tesla1
# Updates the folder using rsync, this script should be run by Tesla1
# This is my editing directory
FirstSource=~/Sumar2016/TE/MMV-Forrit2/
# This is the current directory, where I compile and run the programs on Tesla1
FirstDest=~/Sumar2016/TE/MMV-Forrit2/keyrslurMMV2/
# Here I run the makefile that compiles the programs
make
mv Adal keyrslurMMV2 
cd keyrslurMMV2 
./Adal
#------------------------------------

