#
#-- 64 bit version ----------------------------------------------------
iFortOptions64=-O3 -fimf-arch-consistency=true -fp-model precise -static -openmp -openmp-report2 -static-intel -openmp-link=static

MKLPATH=/opt/intel/mkl/lib/intel64
MKL95PATH=/opt/intel/mkl/include/intel64/lp64

libOptions= -L$(MKLPATH) -I$(MKL95PATH) -lmkl_blas95_lp64 -lmkl_lapack95_lp64\
    -Wl,--start-group $(MKLPATH)/libmkl_intel_lp64.a $(MKLPATH)/libmkl_intel_thread.a $(MKLPATH)/libmkl_core.a -Wl,--end-group -liomp5 -lpthread

LIBDIRS=/usr/local/Slatec
LIBSS=Slatec_AMD64_10p0_LM
#----------------------------------------------------------------------

#-- 32 bit version ----------------------------------------------------
iFortOptions32=-fast -openmp -openmp-report2 -static -static-intel

MKLPATH_32=/opt/intel/mkl/lib/ia32
MKL95PATH_32=/opt/intel/mkl/include/ia32

libOptions_32= -L$(MKLPATH_32) -I$(MKL95PATH_32) -lmkl_blas95 -lmkl_lapack95\
    -Wl,--start-group $(MKLPATH_32)/libmkl_intel.a $(MKLPATH_32)/libmkl_intel_thread.a $(MKLPATH_32)/libmkl_core.a -Wl,--end-group -liomp5 -lpthread

LIBSS_32=Slatec_Intel32_10p1
#----------------------------------------------------------------------


GME_BI_EM_04: Mod_Precision.f90 4cV-MaMvg/Mod_Init.f90 Mod_Fields.f90 PAB.f90 PcAB.f90 PABz.f90 Mod_Matrices_Master_Equation.f90 Math_Mod.f90 addMMct.f90 UAU.f90 GME_BI_EM.f90 

	ifort $(iFortOptions64) -xHost -o GME_BI_EM Mod_Precision.f90 4cV-MaMvg/Mod_Init.f90 Mod_Fields.f90 PAB.f90 PcAB.f90 PABz.f90 Mod_Matrices_Master_Equation.f90 Math_Mod.f90 addMMct.f90 UAU.f90 GME_BI_EM.f90 -L$(LIBDIRS) -l$(LIBSS) $(libOptions)
